spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
    open-in-view: false

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    enabled: false

logging:
  level:
    #  root: WARN
    br.com.judev: DEBUG