spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
    open-in-view: false

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: false

logging:
  level:
    br.com.judev: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

